theme: jekyll-theme-minimal
title: "Carl R. Weinberg"
description: "Author of Red Dynamite: Creationism, Culture Wars, and Anticommunism in America; Adjunct Associate Professor in the Department of History and Senior Lecturer, College of Arts & Sciences at IU Bloomington"
logo: /assets/img/RedDynamiteCover.jpg
